### ISSUE TITLE
Improvement for docker_build

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/github-actions#2]
- [ ] github.ref includes the `slash` e.g. `refs/head/v1.0.0-rc` or `refs/tags/v1.0.0`, we only need tag or branch name
- [ ] better to have default fallback for `component` variable in case of somebody forgot to update it. e.g. github.reponame(but the owner should be excluded)

**Comment by sp3c73r2038** [comment]
supposed to be fixed by #3

- use `${$GITHUB_REPOSITORY##$GITHUB_REPOSITORY_OWNER/}` for component name if `inputs.component` is not set, make it not required too. 
- use `${{ steps.meta.outputs.version }}` from [docker/metadata-action](https://github.com/docker/metadata-action) to remove `refs/heads/` or `refs/tags/` in `github.ref`. and bonus: it replaces `/` with `-` too, in case the branch name is like `some-folder/some-name` .
